# Change these first
owner: ecsistem # Your GitHub organization or username, where this repository lives
repo: bela-tagarela-status # The name of this repository

sites:
  - name: Belatagarela
    url: https://belatagarela.com.br

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: belatagarela.com.br
  baseUrl: /bela-tagarela-status
  logoUrl: https://belatagarela.com.br/assets/logo.5ae61270.svg
  name: Bela Tagarela Status
  introTitle: "Bem Vindo(a) ao Bela Tagarela Status"
  navbar:
    - title: Status
      href: https://ecsistem.github.io/bela-tagarela-status/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
  footer:
  links:
    - title: Sobre
      href: https://belatagarela.com.br/
    - title: Contato
      href: https://belatagarela.com.br/
    - title: Autor
      href: https://instagram.com/ofc_edson_costa
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark # You can set the footer theme to "light" or "dark"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
